# Generated by Django 6.1 on 2026-08-12 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('CREACION', 'Creacion'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable'), ('CAMBIO_PLAZO', 'Cambio de plazo'), ('CAMBIO_PRIORIDAD', 'Cambio de prioridad'), ('COMENTARIO', 'Comentario'), ('ADJUNTO', 'Adjunto')], default='MANUAL', max_length=20)),
                ('descripcion', models.TextField()),
                ('campo', models.CharField(blank=True, max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='bitacora_re_content_dd41ee_idx')],
            },
        ),
    ]
