# Generated by Django 6.1 on 2026-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CREACION', 'Creacion'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_RESPONSABLE', 'Cambio de responsable'), ('CAMBIO_PLAZO', 'Cambio de plazo'), ('CAMBIO_PRIORIDAD', 'Cambio de prioridad'), ('COMENTARIO', 'Comentario'), ('ADJUNTO', 'Adjunto'), ('RECORDATORIO_ENVIADO', 'Recordatorio enviado por correo')], default='MANUAL', max_length=20),
        ),
    ]
