# Generated by Django 6.1 on 2026-08-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_alerta', models.CharField(choices=[('T-3', 'T-3'), ('T-1', 'T-1'), ('Vencido', 'Vencido')], max_length=10)),
                ('fecha_referencia', models.DateField()),
                ('destinatario_correo', models.EmailField(max_length=254)),
                ('exito', models.BooleanField(default=False)),
                ('error_detalle', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-enviado_en'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notificacio_content_c9d495_idx')],
                'unique_together': {('content_type', 'object_id', 'tipo_alerta', 'fecha_referencia')},
            },
        ),
    ]
