# Generated by Django 6.1 on 2026-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='tipo_alerta',
            field=models.CharField(choices=[('T-3', 'T-3'), ('T-1', 'T-1'), ('Vencido', 'Vencido'), ('Manual', 'Manual')], max_length=10),
        ),
    ]
