# Generated by Django 6.1 on 2026-08-13 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='monto_estimado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='tiene_oc',
            field=models.BooleanField(default=False, verbose_name='¿aplica OC?'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='centro_costo',
            field=models.CharField(blank=True, default='U010600213', max_length=100, verbose_name='centro de costo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
