# Generated by Django 6.1 on 2026-08-13 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientointerno',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
